# Generated by Django 2.1.1 on 2018-09-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='context',
            new_name='content',
        ),
    ]
