# Generated by Django 2.1.1 on 2018-10-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181009_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polls',
            name='polls_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.PollsType'),
        ),
    ]
