# Generated by Django 2.1.1 on 2018-10-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181011_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='polls',
            name='polls_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.PollsType'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='polls',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Polls'),
        ),
    ]
